package com.java.moudle.system.domain;


import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.java.until.dba.BaseDomain;

/**
 * 功能菜单(tm_function)
 * 
 * @author tz
 * @version 1.0.0 2020-01-03
 */
@Entity
@Table(name = "tm_function")
public class SysFunction extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = -7635388089043802666L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 唯一标示 */
    @Id
    private String id;

    /** 菜单名称 */
    private String name;

    /** 上级ID */
    private String parentId;

    /** 序号 */
    private String orderNum;

    /** 状态 */
    private String status;

    /** 类型 */
    private String type;

    /** 路径 */
    private String url;
    
    private String icon;
    
    @Transient
    private List<SysFunction> funList;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取唯一标示
     * 
     * @return 唯一标示
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置唯一标示
     * 
     * @param id
     *          唯一标示
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取菜单名称
     * 
     * @return 菜单名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置菜单名称
     * 
     * @param name
     *          菜单名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取上级ID
     * 
     * @return 上级ID
     */
    public String getParentId() {
        return this.parentId;
    }

    /**
     * 设置上级ID
     * 
     * @param parentId
     *          上级ID
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * 获取序号
     * 
     * @return 序号
     */
    public String getOrderNum() {
        return this.orderNum;
    }

    /**
     * 设置序号
     * 
     * @param orderNum
     *          序号
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * 获取状态
     * 
     * @return 状态
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 设置状态
     * 
     * @param status
     *          状态
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 获取类型
     * 
     * @return 类型
     */
    public String getType() {
        return this.type;
    }

    /**
     * 设置类型
     * 
     * @param type
     *          类型
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * 获取路径
     * 
     * @return 路径
     */
    public String getUrl() {
        return this.url;
    }

    public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
     * 设置路径
     * 
     * @param url
     *          路径
     */
    public void setUrl(String url) {
        this.url = url;
    }

	public List<SysFunction> getFunList() {
		return funList;
	}

	public void setFunList(List<SysFunction> funList) {
		this.funList = funList;
	}

    /* This code was generated by TableGo tools, mark 2 end. */
}