package com.java.moudle.system.domain;


import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.java.until.dba.BaseDomain;

/**
 * 角色功能关联表(tm_role_function)
 * 
 * @author tz
 * @version 1.0.0 2020-01-03
 */
@Entity
@Table(name = "tm_role_function")
public class SysRoleFunction extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = 2372248623069294836L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 唯一标示 */
    @Id
    private String id;

    /** 角色ID */
    private String roleId;

    /** 功能ID */
    private String functionId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取唯一标示
     * 
     * @return 唯一标示
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置唯一标示
     * 
     * @param id
     *          唯一标示
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取角色ID
     * 
     * @return 角色ID
     */
    public String getRoleId() {
        return this.roleId;
    }

    /**
     * 设置角色ID
     * 
     * @param roleId
     *          角色ID
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * 获取功能ID
     * 
     * @return 功能ID
     */
    public String getFunctionId() {
        return this.functionId;
    }

    /**
     * 设置功能ID
     * 
     * @param functionId
     *          功能ID
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}