package com.java.moudle.system.domain;


import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.java.until.dba.BaseDomain;

/**
 * 用户角色关联表(tm_user_role)
 * 
 * @author tz
 * @version 1.0.0 2020-01-03
 */
@Entity
@Table(name = "tm_user_role")
public class SysUserRole extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = -7457647212924418494L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 唯一标识 */
    @Id
    private String id;

    /** 用户ID */
    private String userId;

    /** 角色ID */
    private String roleId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取唯一标识
     * 
     * @return 唯一标识
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置唯一标识
     * 
     * @param id
     *          唯一标识
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取用户ID
     * 
     * @return 用户ID
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * 设置用户ID
     * 
     * @param userId
     *          用户ID
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * 获取角色ID
     * 
     * @return 角色ID
     */
    public String getRoleId() {
        return this.roleId;
    }

    /**
     * 设置角色ID
     * 
     * @param roleId
     *          角色ID
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}