package com.java.moudle.system.domain;


import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.java.until.dba.BaseDomain;

/**
 * 临床信息模板(tm_clin_model)
 * 
 * @author tz
 * @version 1.0.0 2020-01-03
 */
@Entity
@Table(name = "tm_clin_model")
public class TmClinModel extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = -695502541022624607L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 唯一辨识 */
    @Id
    private String id;

    /** 机构ID */
    private String orgId;

    /** 科室ID */
    private String depId;

    /** 类型 1、主诉 2、现病史 3、既往史 4、过敏史 5、家族史 6、查体 7、辅助检查 8、治疗经过 9、备注 */
    private String type;

    /** 临床信息描述 */
    private String depict;

    private String title;//标题
    
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取唯一辨识
     * 
     * @return 唯一辨识
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置唯一辨识
     * 
     * @param id
     *          唯一辨识
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取机构ID
     * 
     * @return 机构ID
     */
    public String getOrgId() {
        return this.orgId;
    }

    /**
     * 设置机构ID
     * 
     * @param orgId
     *          机构ID
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * 获取科室ID
     * 
     * @return 科室ID
     */
    public String getDepId() {
        return this.depId;
    }

    /**
     * 设置科室ID
     * 
     * @param depId
     *          科室ID
     */
    public void setDepId(String depId) {
        this.depId = depId;
    }

    /**
     * 获取类型 1、主诉 2、现病史 3、既往史 4、过敏史 5、家族史 6、查体 7、辅助检查 8、治疗经过 9、备注
     * 
     * @return 类型 1、主诉 2、现病史 3、既往史 4、过敏史 5、家族史 6、查体 7、辅助检查 8、治疗经过 9、备注
     */
    public String getType() {
        return this.type;
    }

    /**
     * 设置类型 1、主诉 2、现病史 3、既往史 4、过敏史 5、家族史 6、查体 7、辅助检查 8、治疗经过 9、备注
     * 
     * @param type
     *          类型 1、主诉 2、现病史 3、既往史 4、过敏史 5、家族史 6、查体 7、辅助检查 8、治疗经过 9、备注
     */
    public void setType(String type) {
        this.type = type;
    }
    
    /**
     * 获取临床信息描述
     * 
     * @return 临床信息描述
     */
	public String getDepict() {
		return depict;
	}

	public void setDepict(String depict) {
		this.depict = depict;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

    /* This code was generated by TableGo tools, mark 2 end. */
}