package com.java.moudle.tripart.hcplatform.dto;


import java.io.Serializable;
import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;
import com.java.until.dict.DictUtil;


public class TmTurnDto implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -7654512377404281757L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private String id;//唯一标识
    private String type;//类型 1.转出 2.回转
    private String billName;//双向转诊的名称
    private String docName;//医生姓名
    private String orgName;//医院名称
    private String depName;//科室名称
    @JSONField(format="yyyy-MM-dd")
    private Date checkTime;//就诊时间
    private String accDocName;//接诊医生
    private String accOrgName;//接诊医院名称
    private String accDepName;//接诊科室名称
    private String refPurpose;//转诊目的
    private String diaCode;//诊断编码
    private String firstImpression;//初步印象
    private String name;//患者名称
    private String sfzh;//身份证号
    private String age;//年龄
    private String sex;//性别
    private String birthday;//生日
    private String dno;//档案编号
    private String telephone;//联系方式
    private String familyPhone;//家属联系方式
    /** 家庭详细住址 */
    private String adress;
    /** 家庭住址 */
    private String province;
    private String city;
    private String county;
    private String town;
    private String zs;//主诉
    private String xbs;//现病史
    private String jwz;//既往史
    private String gms;//过敏史
    private String jzs;//家族史
    private String ct;//查体
    private String fzjc;//辅助检查
    private String zljg;//治疗经过
    private String remark;//备注
    @JSONField(format="yyyy-MM-dd")
    private Date createTime;//创建时间
    @JSONField(format="yyyy-MM-dd")
    private Date updateTime;//更新时间
    private String jcjg;//检查结果
    private String kfjy;//康复建议
    private String provinceName;
    private String cityName;
    private String countyName;
    private String townName;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getBillName() {
		return billName;
	}
	public void setBillName(String billName) {
		this.billName = billName;
	}
	public String getDocName() {
		return docName;
	}
	public void setDocName(String docName) {
		this.docName = docName;
	}
	public String getOrgName() {
		return orgName;
	}
	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}
	public String getDepName() {
		return depName;
	}
	public void setDepName(String depName) {
		this.depName = depName;
	}
	public Date getCheckTime() {
		return checkTime;
	}
	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}
	public String getAccDocName() {
		return accDocName;
	}
	public void setAccDocName(String accDocName) {
		this.accDocName = accDocName;
	}
	public String getAccOrgName() {
		return accOrgName;
	}
	public void setAccOrgName(String accOrgName) {
		this.accOrgName = accOrgName;
	}
	public String getAccDepName() {
		return accDepName;
	}
	public void setAccDepName(String accDepName) {
		this.accDepName = accDepName;
	}
	public String getRefPurpose() {
		return refPurpose;
	}
	public void setRefPurpose(String refPurpose) {
		this.refPurpose = refPurpose;
	}
	public String getDiaCode() {
		return diaCode;
	}
	public void setDiaCode(String diaCode) {
		this.diaCode = diaCode;
	}
	public String getFirstImpression() {
		return firstImpression;
	}
	public void setFirstImpression(String firstImpression) {
		this.firstImpression = firstImpression;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getSfzh() {
		return sfzh;
	}
	public void setSfzh(String sfzh) {
		this.sfzh = sfzh;
	}
	public String getAge() {
		return age;
	}
	public void setAge(String age) {
		this.age = age;
	}
	public String getSex() {
		return sex;
	}
	public void setSex(String sex) {
		this.sex = sex;
	}
	public String getBirthday() {
		return birthday;
	}
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}
	public String getDno() {
		return dno;
	}
	public void setDno(String dno) {
		this.dno = dno;
	}
	public String getTelephone() {
		return telephone;
	}
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}
	public String getFamilyPhone() {
		return familyPhone;
	}
	public void setFamilyPhone(String familyPhone) {
		this.familyPhone = familyPhone;
	}
	public String getAdress() {
		return adress;
	}
	public void setAdress(String adress) {
		this.adress = adress;
	}
	
	public String getProvince() {
		return province;
	}
	public void setProvince(String province) {
		this.provinceName = DictUtil.getDictValue("areadict", province);
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.cityName = DictUtil.getDictValue("areadict", city);
		this.city = city;
	}

	public String getCounty() {
		return county;
	}

	public void setCounty(String county) {
		this.countyName = DictUtil.getDictValue("areadict", county);
		this.county = county;
	}

	public String getTown() {
		return town;
	}

	public void setTown(String town) {
		this.townName = DictUtil.getDictValue("areadict", town);
		this.town = town;
	}
	public String getZs() {
		return zs;
	}
	public void setZs(String zs) {
		this.zs = zs;
	}
	public String getXbs() {
		return xbs;
	}
	public void setXbs(String xbs) {
		this.xbs = xbs;
	}
	public String getJwz() {
		return jwz;
	}
	public void setJwz(String jwz) {
		this.jwz = jwz;
	}
	public String getGms() {
		return gms;
	}
	public void setGms(String gms) {
		this.gms = gms;
	}
	public String getJzs() {
		return jzs;
	}
	public void setJzs(String jzs) {
		this.jzs = jzs;
	}
	public String getCt() {
		return ct;
	}
	public void setCt(String ct) {
		this.ct = ct;
	}
	public String getFzjc() {
		return fzjc;
	}
	public void setFzjc(String fzjc) {
		this.fzjc = fzjc;
	}
	public String getZljg() {
		return zljg;
	}
	public void setZljg(String zljg) {
		this.zljg = zljg;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Date getUpdateTime() {
		return updateTime;
	}
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	public String getJcjg() {
		return jcjg;
	}
	public void setJcjg(String jcjg) {
		this.jcjg = jcjg;
	}
	public String getKfjy() {
		return kfjy;
	}
	public void setKfjy(String kfjy) {
		this.kfjy = kfjy;
	}
	public String getProvinceName() {
		return provinceName;
	}
	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}
	public String getCityName() {
		return cityName;
	}
	public void setCityName(String cityName) {
		this.cityName = cityName;
	}
	public String getCountyName() {
		return countyName;
	}
	public void setCountyName(String countyName) {
		this.countyName = countyName;
	}
	public String getTownName() {
		return townName;
	}
	public void setTownName(String townName) {
		this.townName = townName;
	}
    
    
}