package com.java.moudle.trunback.domain;


import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.java.moudle.system.domain.TmFileUpload;
import com.java.until.dba.BaseDomain;
import com.java.until.dict.DictUtil;

/**
 * 	回转管理表(tm_turn_rotary)
 * 
 * @author tz
 * @version 1.0.0 2020-01-03
 */
@Entity
@Table(name = "tm_turn_rotary")
public class TmTurnRotary extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = -7654555577404281757L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 唯一标识 */
    @Id
    private String id;

    /** 转出ID */
    private String outId;

    /** 转入ID */
    private String inId;

    /** 机构ID */
    private String orgId;

    /** 科室ID */
    private String depId;

    /** 医生姓名 */
    private String docName;
    
    /** 医生id */
    private String docId;

    /** 就诊时间 */
    @JSONField(format="yyyy-MM-dd")
    private Date checkTime;

    /** 接诊医院ID */
    private String accOrgId;

    /** 接诊科室ID */
    private String accDepId;

    /** 接诊医生 */
    private String accDocName;
    
    /** 接诊医生标识 */
    private String accDocId;

    /** 转诊目的 */
    private String refPurpose;

    /** 诊断编码 */
    private String diaCode;

    /** 初步印象 */
    private String firstImpression;

    /** 患者名称 */
    private String name;

    /** 身份证号 */
    private String sfzh;

    /** 年龄 */
    private String age;

    /** 性别 */
    private String sex;

    /** 生日 */
    private String birthday;

    /** 体重 */
    private String weight;

    /** 身高 */
    private String height;

    /** 档案编号 */
    private String dno;

    /** 联系方式 */
    private String telephone;

    /** 家属联系方式 */
    private String familyPhone;

    /** 医保卡 */
    private String healthCard;

    /** 医报类型 */
    private String healthType;

    /** 家庭详细住址 */
    private String adress;
    
    /** 家庭住址 */
    private String province;
    private String city;
    private String county;
    private String town;

    /** 主诉 */
    private String zs;

    /** 现病史 */
    private String xbs;

    /** 既往史 */
    private String jwz;

    /** 过敏史 */
    private String gms;

    /** 家族史 */
    private String jzs;

    /** 查体 */
    private String ct;

    /** 辅助检查 */
    private String fzjc;

    /** 治疗经过 */
    private String zljg;

    /** 备注 */
    private String remark;

    /** 创建人 */
    @Column(updatable = false)
    private String createUser;

    /** 创建时间 */
    @Column(updatable = false)
    @JSONField(format="yyyy-MM-dd")
    private Date createTime;
    
    /** 创建人 */
    @Column(updatable = false)
    private String InCreateUser;

    /** 创建时间 */
    @Column(updatable = false)
    @JSONField(format="yyyy-MM-dd")
    private Date InCreateTime;

    /** 转入审核状态 */
    private String inStatus;

    /** 转入审核人 */
    private String inAuditUser;

    /** 转入审核时间 */
    @JSONField(format="yyyy-MM-dd")
    private Date inAuditTime;

    /** 转入审核原因 */
    private String inAuditReason;

    /** 转出审核状态 */
    private String outStatus;

    /** 转出审核人 */
    private String outAuditUser;

    /** 转出审核时间 */
    @JSONField(format="yyyy-MM-dd")
    private Date outAuditTime;

    /** 转出审核原因 */
    private String outAuditReason;

    /** 修改人 */
    private String updateUser;

    /** 修改时间 */
    @JSONField(format="yyyy-MM-dd")
    private Date updateTime;

    /** 删除标识 */
    @Column(updatable = false)
    private String deleteFlg;
    
    private String jcjg;//检查结果
    private String kfjy;//康复建议
	@Column(updatable = false)
	private String auditType;//是否开启院内审核（0.关闭 1.开启）

    @Transient
    private List<TmFileUpload> filelist;
    @Transient
    private String filelistStr;
    
    @Transient
    private String roleType;
    @Transient
    private String startDate;
    @Transient
    private String endDate;
    @Transient
    private String nameOrSfzh;
    @Transient
    private String orgName;
    @Transient
    private String depName;
    @Transient
    private String accOrgName;
    @Transient
    private String accDepName;
    @Transient
    private String inStatusName;
    @Transient
    private String outStatusName;
    @Transient
    private String provinceName;
    @Transient
    private String cityName;
    @Transient
    private String countyName;
    @Transient
    private String townName;
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取唯一标识
     * 
     * @return 唯一标识
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置唯一标识
     * 
     * @param id
     *          唯一标识
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取转出ID
     * 
     * @return 转出ID
     */
    public String getOutId() {
        return this.outId;
    }

    /**
     * 设置转出ID
     * 
     * @param outId
     *          转出ID
     */
    public void setOutId(String outId) {
        this.outId = outId;
    }

    /**
     * 获取转入ID
     * 
     * @return 转入ID
     */
    public String getInId() {
        return this.inId;
    }

    /**
     * 设置转入ID
     * 
     * @param inId
     *          转入ID
     */
    public void setInId(String inId) {
        this.inId = inId;
    }

    /**
     * 获取机构ID
     * 
     * @return 机构ID
     */
    public String getOrgId() {
        return this.orgId;
    }

    /**
     * 设置机构ID
     * 
     * @param orgId
     *          机构ID
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * 获取科室ID
     * 
     * @return 科室ID
     */
    public String getDepId() {
        return this.depId;
    }

    /**
     * 设置科室ID
     * 
     * @param depId
     *          科室ID
     */
    public void setDepId(String depId) {
        this.depId = depId;
    }

    /**
     * 获取医生姓名
     * 
     * @return 医生姓名
     */
    public String getDocName() {
        return this.docName;
    }

    /**
     * 设置医生姓名
     * 
     * @param docName
     *          医生姓名
     */
    public void setDocName(String docName) {
        this.docName = docName;
    }

    public String getDocId() {
		return docId;
	}

	public void setDocId(String docId) {
		this.docId = docId;
	}

	/**
     * 获取就诊时间
     * 
     * @return 就诊时间
     */
    public Date getCheckTime() {
        return this.checkTime;
    }

    /**
     * 设置就诊时间
     * 
     * @param checkTime
     *          就诊时间
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * 获取接诊医院ID
     * 
     * @return 接诊医院ID
     */
    public String getAccOrgId() {
        return this.accOrgId;
    }

    /**
     * 设置接诊医院ID
     * 
     * @param accOrgId
     *          接诊医院ID
     */
    public void setAccOrgId(String accOrgId) {
        this.accOrgId = accOrgId;
    }

    /**
     * 获取接诊科室ID
     * 
     * @return 接诊科室ID
     */
    public String getAccDepId() {
        return this.accDepId;
    }

    /**
     * 设置接诊科室ID
     * 
     * @param accDepId
     *          接诊科室ID
     */
    public void setAccDepId(String accDepId) {
        this.accDepId = accDepId;
    }

    /**
     * 获取接诊医生
     * 
     * @return 接诊医生
     */
    public String getAccDocName() {
        return this.accDocName;
    }

    /**
     * 设置接诊医生
     * 
     * @param accDocName
     *          接诊医生
     */
    public void setAccDocName(String accDocName) {
        this.accDocName = accDocName;
    }

    public String getAccDocId() {
		return accDocId;
	}

	public void setAccDocId(String accDocId) {
		this.accDocId = accDocId;
	}

	/**
     * 获取转诊目的
     * 
     * @return 转诊目的
     */
    public String getRefPurpose() {
        return this.refPurpose;
    }

    /**
     * 设置转诊目的
     * 
     * @param refPurpose
     *          转诊目的
     */
    public void setRefPurpose(String refPurpose) {
        this.refPurpose = refPurpose;
    }

    /**
     * 获取诊断编码
     * 
     * @return 诊断编码
     */
    public String getDiaCode() {
        return this.diaCode;
    }

    /**
     * 设置诊断编码
     * 
     * @param diaCode
     *          诊断编码
     */
    public void setDiaCode(String diaCode) {
        this.diaCode = diaCode;
    }

    /**
     * 获取初步印象
     * 
     * @return 初步印象
     */
    public String getFirstImpression() {
        return this.firstImpression;
    }

    /**
     * 设置初步印象
     * 
     * @param firstImpression
     *          初步印象
     */
    public void setFirstImpression(String firstImpression) {
        this.firstImpression = firstImpression;
    }

    /**
     * 获取患者名称
     * 
     * @return 患者名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置患者名称
     * 
     * @param name
     *          患者名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取身份证号
     * 
     * @return 身份证号
     */
    public String getSfzh() {
        return this.sfzh;
    }

    /**
     * 设置身份证号
     * 
     * @param sfzh
     *          身份证号
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh;
    }

    /**
     * 获取年龄
     * 
     * @return 年龄
     */
    public String getAge() {
        return this.age;
    }

    /**
     * 设置年龄
     * 
     * @param age
     *          年龄
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * 获取性别
     * 
     * @return 性别
     */
    public String getSex() {
        return this.sex;
    }

    /**
     * 设置性别
     * 
     * @param sex
     *          性别
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * 获取生日
     * 
     * @return 生日
     */
    public String getBirthday() {
        return this.birthday;
    }

    /**
     * 设置生日
     * 
     * @param birthday
     *          生日
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * 获取体重
     * 
     * @return 体重
     */
    public String getWeight() {
        return this.weight;
    }

    /**
     * 设置体重
     * 
     * @param weight
     *          体重
     */
    public void setWeight(String weight) {
        this.weight = weight;
    }

    /**
     * 获取身高
     * 
     * @return 身高
     */
    public String getHeight() {
        return this.height;
    }

    /**
     * 设置身高
     * 
     * @param height
     *          身高
     */
    public void setHeight(String height) {
        this.height = height;
    }

    /**
     * 获取档案编号
     * 
     * @return 档案编号
     */
    public String getDno() {
        return this.dno;
    }

    /**
     * 设置档案编号
     * 
     * @param dno
     *          档案编号
     */
    public void setDno(String dno) {
        this.dno = dno;
    }

    /**
     * 获取联系方式
     * 
     * @return 联系方式
     */
    public String getTelephone() {
        return this.telephone;
    }

    /**
     * 设置联系方式
     * 
     * @param telephone
     *          联系方式
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * 获取家属联系方式
     * 
     * @return 家属联系方式
     */
    public String getFamilyPhone() {
        return this.familyPhone;
    }

    /**
     * 设置家属联系方式
     * 
     * @param familyPhone
     *          家属联系方式
     */
    public void setFamilyPhone(String familyPhone) {
        this.familyPhone = familyPhone;
    }

    /**
     * 获取医保卡
     * 
     * @return 医保卡
     */
    public String getHealthCard() {
        return this.healthCard;
    }

    /**
     * 设置医保卡
     * 
     * @param healthCard
     *          医保卡
     */
    public void setHealthCard(String healthCard) {
        this.healthCard = healthCard;
    }

    /**
     * 获取医报类型
     * 
     * @return 医报类型
     */
    public String getHealthType() {
        return this.healthType;
    }

    /**
     * 设置医报类型
     * 
     * @param healthType
     *          医报类型
     */
    public void setHealthType(String healthType) {
        this.healthType = healthType;
    }

    /**
     * 获取家庭住址
     * 
     * @return 家庭住址
     */
    public String getAdress() {
        return this.adress;
    }

    /**
     * 设置家庭住址
     * 
     * @param adress
     *          家庭住址
     */
    public void setAdress(String adress) {
        this.adress = adress;
    }

    public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.provinceName = DictUtil.getDictValue("areadict", province);
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.cityName = DictUtil.getDictValue("areadict", city);
		this.city = city;
	}

	public String getCounty() {
		return county;
	}

	public void setCounty(String county) {
		this.countyName = DictUtil.getDictValue("areadict", county);
		this.county = county;
	}

	public String getTown() {
		return town;
	}

	public void setTown(String town) {
		this.townName = DictUtil.getDictValue("areadict", town);
		this.town = town;
	}

	/**
     * 获取主诉
     * 
     * @return 主诉
     */
    public String getZs() {
        return this.zs;
    }

    /**
     * 设置主诉
     * 
     * @param zs
     *          主诉
     */
    public void setZs(String zs) {
        this.zs = zs;
    }

    /**
     * 获取现病史
     * 
     * @return 现病史
     */
    public String getXbs() {
        return this.xbs;
    }

    /**
     * 设置现病史
     * 
     * @param xbs
     *          现病史
     */
    public void setXbs(String xbs) {
        this.xbs = xbs;
    }

    /**
     * 获取既往史
     * 
     * @return 既往史
     */
    public String getJwz() {
        return this.jwz;
    }

    /**
     * 设置既往史
     * 
     * @param jwz
     *          既往史
     */
    public void setJwz(String jwz) {
        this.jwz = jwz;
    }

    /**
     * 获取过敏史
     * 
     * @return 过敏史
     */
    public String getGms() {
        return this.gms;
    }

    /**
     * 设置过敏史
     * 
     * @param gms
     *          过敏史
     */
    public void setGms(String gms) {
        this.gms = gms;
    }

    /**
     * 获取家族史
     * 
     * @return 家族史
     */
    public String getJzs() {
        return this.jzs;
    }

    /**
     * 设置家族史
     * 
     * @param jzs
     *          家族史
     */
    public void setJzs(String jzs) {
        this.jzs = jzs;
    }

    /**
     * 获取查体
     * 
     * @return 查体
     */
    public String getCt() {
        return this.ct;
    }

    /**
     * 设置查体
     * 
     * @param ct
     *          查体
     */
    public void setCt(String ct) {
        this.ct = ct;
    }

    /**
     * 获取辅助检查
     * 
     * @return 辅助检查
     */
    public String getFzjc() {
        return this.fzjc;
    }

    /**
     * 设置辅助检查
     * 
     * @param fzjc
     *          辅助检查
     */
    public void setFzjc(String fzjc) {
        this.fzjc = fzjc;
    }

    /**
     * 获取治疗经过
     * 
     * @return 治疗经过
     */
    public String getZljg() {
        return this.zljg;
    }

    /**
     * 设置治疗经过
     * 
     * @param zljg
     *          治疗经过
     */
    public void setZljg(String zljg) {
        this.zljg = zljg;
    }

    /**
     * 获取备注
     * 
     * @return 备注
     */
    public String getRemark() {
        return this.remark;
    }

    /**
     * 设置备注
     * 
     * @param remark
     *          备注
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * 获取创建人
     * 
     * @return 创建人
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * 设置创建人
     * 
     * @param createUser
     *          创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置创建时间
     * 
     * @param createTime
     *          创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getInCreateUser() {
		return InCreateUser;
	}

	public void setInCreateUser(String inCreateUser) {
		InCreateUser = inCreateUser;
	}

	public Date getInCreateTime() {
		return InCreateTime;
	}

	public void setInCreateTime(Date inCreateTime) {
		InCreateTime = inCreateTime;
	}

	/**
     * 获取转入审核状态
     * 
     * @return 转入审核状态
     */
    public String getInStatus() {
        return this.inStatus;
    }

    /**
     * 设置转入审核状态
     * 
     * @param inStatus
     *          转入审核状态
     */
    public void setInStatus(String inStatus) {
        this.inStatus = inStatus;
    }

    /**
     * 获取转入审核人
     * 
     * @return 转入审核人
     */
    public String getInAuditUser() {
        return this.inAuditUser;
    }

    /**
     * 设置转入审核人
     * 
     * @param inAuditUser
     *          转入审核人
     */
    public void setInAuditUser(String inAuditUser) {
        this.inAuditUser = inAuditUser;
    }

    /**
     * 获取转入审核时间
     * 
     * @return 转入审核时间
     */
    public Date getInAuditTime() {
        return this.inAuditTime;
    }

    /**
     * 设置转入审核时间
     * 
     * @param inAuditTime
     *          转入审核时间
     */
    public void setInAuditTime(Date inAuditTime) {
        this.inAuditTime = inAuditTime;
    }

    /**
     * 获取转入审核原因
     * 
     * @return 转入审核原因
     */
    public String getInAuditReason() {
        return this.inAuditReason;
    }

    /**
     * 设置转入审核原因
     * 
     * @param inAuditReason
     *          转入审核原因
     */
    public void setInAuditReason(String inAuditReason) {
        this.inAuditReason = inAuditReason;
    }

    /**
     * 获取转出审核状态
     * 
     * @return 转出审核状态
     */
    public String getOutStatus() {
        return this.outStatus;
    }

    /**
     * 设置转出审核状态
     * 
     * @param outStatus
     *          转出审核状态
     */
    public void setOutStatus(String outStatus) {
        this.outStatus = outStatus;
    }

    /**
     * 获取转出审核人
     * 
     * @return 转出审核人
     */
    public String getOutAuditUser() {
        return this.outAuditUser;
    }

    /**
     * 设置转出审核人
     * 
     * @param outAuditUser
     *          转出审核人
     */
    public void setOutAuditUser(String outAuditUser) {
        this.outAuditUser = outAuditUser;
    }

    /**
     * 获取转出审核时间
     * 
     * @return 转出审核时间
     */
    public Date getOutAuditTime() {
        return this.outAuditTime;
    }

    /**
     * 设置转出审核时间
     * 
     * @param outAuditTime
     *          转出审核时间
     */
    public void setOutAuditTime(Date outAuditTime) {
        this.outAuditTime = outAuditTime;
    }

    /**
     * 获取转出审核原因
     * 
     * @return 转出审核原因
     */
    public String getOutAuditReason() {
        return this.outAuditReason;
    }

    /**
     * 设置转出审核原因
     * 
     * @param outAuditReason
     *          转出审核原因
     */
    public void setOutAuditReason(String outAuditReason) {
        this.outAuditReason = outAuditReason;
    }

    /**
     * 获取修改人
     * 
     * @return 修改人
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * 设置修改人
     * 
     * @param updateUser
     *          修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * 获取修改时间
     * 
     * @return 修改时间
     */
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * 设置修改时间
     * 
     * @param updateTime
     *          修改时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取删除标识
     * 
     * @return 删除标识
     */
    public String getDeleteFlg() {
        return this.deleteFlg;
    }

    /**
     * 设置删除标识
     * 
     * @param deleteFlg
     *          删除标识
     */
    public void setDeleteFlg(String deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

	public String getJcjg() {
		return jcjg;
	}

	public void setJcjg(String jcjg) {
		this.jcjg = jcjg;
	}

	public String getKfjy() {
		return kfjy;
	}

	public void setKfjy(String kfjy) {
		this.kfjy = kfjy;
	}

	public String getAuditType() {
		return auditType;
	}

	public void setAuditType(String auditType) {
		this.auditType = auditType;
	}

	public String getRoleType() {
		return roleType;
	}

	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getNameOrSfzh() {
		return nameOrSfzh;
	}

	public void setNameOrSfzh(String nameOrSfzh) {
		this.nameOrSfzh = nameOrSfzh;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getDepName() {
		return depName;
	}

	public void setDepName(String depName) {
		this.depName = depName;
	}

	public String getAccOrgName() {
		return accOrgName;
	}

	public void setAccOrgName(String accOrgName) {
		this.accOrgName = accOrgName;
	}

	public String getAccDepName() {
		return accDepName;
	}

	public void setAccDepName(String accDepName) {
		this.accDepName = accDepName;
	}

	public String getInStatusName() {
		return inStatusName;
	}

	public void setInStatusName(String inStatusName) {
		this.inStatusName = inStatusName;
	}

	public String getOutStatusName() {
		return outStatusName;
	}

	public void setOutStatusName(String outStatusName) {
		this.outStatusName = outStatusName;
	}

	public List<TmFileUpload> getFilelist() {
		return filelist;
	}

	public void setFilelist(List<TmFileUpload> filelist) {
		this.filelist = filelist;
	}

	public String getFilelistStr() {
		return filelistStr;
	}

	public void setFilelistStr(String filelistStr) {
		this.filelistStr = filelistStr;
	}

	public String getProvinceName() {
		return provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getCountyName() {
		return countyName;
	}

	public void setCountyName(String countyName) {
		this.countyName = countyName;
	}

	public String getTownName() {
		return townName;
	}

	public void setTownName(String townName) {
		this.townName = townName;
	}

    /* This code was generated by TableGo tools, mark 2 end. */
}